### ISSUE TITLE
Broken acknowledgements PDF link

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#195]
https://ocwnext.odl.mit.edu/courses/8-02-physics-ii-electricity-and-magnetism-spring-2007/

Open the course description and scroll to the bottom. At the end of the acknowledgements there's a PDF link which is broken.

**Comment by gumaerc** [comment]
If you look in the parsed json for this course, this link is an absolute link that looks like this:

`(<a href=\"/courses/physics/8-02-physics-ii-electricity-and-magnetism-spring-2007/acknowledgements.pdf\">PDF</a>)`

The reason a PDF viewer page for this is not being rendered is because the source `course_files` object a `parent_uid` that is equal to the course UID:

```
  {
    "order_index": null,
    "uid": "d7d1fabcb57a6d4a9cc96f04348dedfd",
    "id": "acknowledgements.pdf",
    "parent_uid": "8d3bdda7363b3a4b18d9d5b7c4083899",
    "title": "acknowledgements.pdf",
    "caption": null,
    "file_type": "application/pdf",
    "alt_text": null,
    "credit": null,
    "platform_requirements": "",
    "description": "This resource contains acknowledgements to the persons who helped build this course.",
    "type": "OCWFile",
    "file_location": "https://open-learning-course-data-production.s3.amazonaws.com/8-02-physics-ii-electricity-and-magnetism-spring-2007/d7d1fabcb57a6d4a9cc96f04348dedfd_acknowledgements.pdf"
  }
```

PDF pages are rendered during the recursive loop of course pages, and course files are filtered on having a `file_type` of `application/pdf` and a `parent_id` equal to the course page being rendered:

```
  const pdfFiles = courseData["course_files"].filter(
    file =>
      file["file_type"] === "application/pdf" &&
      file["parent_uid"] === page["uid"]
  )
```

We need to also scan for PDF files linked in the course home data and generate pages for those as well.
