### ISSUE TITLE
Underscores aren't handled correctly in links

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#233]
### Steps to Reproduce

https://ocwnext.odl.mit.edu/courses/12-335-experimental-atmospheric-chemistry-fall-2014/sections/labs/

Under Section 3: Aerosols and Clouds, links contain escape characters where they shouldn't (see screenshot).

### Expected Behavior

The first link text should be `Lab 3_1 Handout (PDF)`. The second link should also have the backslash removed.

### Actual Behavior

The links show up like `Lab 3\_1 Handout (PDF)`

### Context
This is the HTML from the parsed JSON: `<a href=\"./resolveuid/8f754fe0f3f7cb2e8e80508560325220\">Lab 3_1 Handout (PDF)</a>`. 

### Screenshot or Screencast

![Screenshot from 2021-03-19 12-06-04](https://user-images.githubusercontent.com/863262/111810023-f2400880-88ab-11eb-9b9b-aaa93b803dc5.png)

**Comment by gumaerc** [comment]
I think this will be fixed by [this](https://github.com/mitodl/ocw-to-hugo/pull/230) PR.  This is what it looks like running  the theme with this course locally against the branch of `ocw-to-hugo` in the PR:

![image](https://user-images.githubusercontent.com/12089658/111811181-2cf67080-88ad-11eb-9acb-aab9d7f72639.png)

**Comment by noisecapella** [comment]
@gumaerc yes you're right, I was looking at the wrong output
