### ISSUE TITLE
Video Gallery all caps

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#285]
### Steps to Reproduce

Take a look at the video galleries in https://ocwnext.odl.mit.edu/courses/ec-711-d-lab-energy-spring-2011/sections/energy-storage/ 

### Expected Behavior

- Text should be regular case, without the `upppercase` CSS style. 
- Take a look at other video galleries in nextgen, like https://ocwnext.odl.mit.edu/courses/cms-611j-creating-video-games-fall-2014/sections/lecture-videos/
- Take a look at the legacy version of broken case: https://ocw.mit.edu/courses/edgerton-center/ec-711-d-lab-energy-spring-2011/intro-energy-basics-human-power/

### Screenshot 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/430126/118814207-e35edd80-b87d-11eb-9ad6-f416796b14ec.png">

**Comment by MAbdurrehman12** [comment]
@pdpinch The link (https://ocwnext.odl.mit.edu/courses/ec-711-d-lab-energy-spring-2011/sections/energy-storage/) provided above seems to be broken:
![image](https://user-images.githubusercontent.com/93309234/149098021-cddc1ecd-1e8d-4088-99c9-0bf8518611a6.png)

However if I go to this link (), I'm only seeing video title (which is not in all caps) and not seeing any description.
![image](https://user-images.githubusercontent.com/93309234/149098378-b82707f4-fee5-440a-836c-68faee4bf518.png)

I also fetched the course content from github and ran it locally but the view as same

Do you have any suggestion on how to reproduce the issue or Is there anything I'm doing wrong?  
Maybe this ticket is old and there have been some changes since then?

**Comment by pdpinch** [comment]
Sorry about that. Here is the correct link: https://ocwnext.odl.mit.edu/courses/ec-711-d-lab-energy-spring-2011/video_galleries/energy-storage/

It looks like this has already been fixed.
