### ISSUE TITLE
Table not rendered correctly

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#357]
https://ocwnext.odl.mit.edu/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/pages/reactions-and-kinetics/23-reaction-rates/

If you look at the legacy site https://ocw.mit.edu/courses/materials-science-and-engineering/3-091sc-introduction-to-solid-state-chemistry-fall-2010/reactions-and-kinetics/23-reaction-rates/ there is a table. We seem to be creating markdown for tables based on the `|` characters but something is preventing it from actually getting rendered as an table

**Comment by pdpinch** [comment]
FWIW, there seems to a sc-specific table style, with `class="sc_overview"`

**Comment by pdpinch** [comment]
@gumaerc let me know if you think this will be fixed by #429

**Comment by pdpinch** [comment]
This looks ok to me here https://ocw-draft-qa.global.ssl.fastly.net/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/pages/reactions-and-kinetics/23-reaction-rates/

We can close this once the changes make it to production.

**Comment by gumaerc** [comment]
@pdpinch Yes, it looks like this was fixed by my recent changes to table rendering.  The changes are in production (https://ocw-published.odl.mit.edu/courses/3-091sc-introduction-to-solid-state-chemistry-fall-2010/pages/reactions-and-kinetics/23-reaction-rates/) so I'll close this issue.  There should be no tables remaining at this point that use the markdown table syntax.
