### ISSUE TITLE
Duplicate courses on production 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#443]
### Steps to Reproduce

1. look at the new courses carousel on  https://ocw-published.odl.mit.edu/

### Expected Behavior

- 4 different courses

### Actual Behavior

- The first two courses appear to be the same. 

I'm not sure if this is a bug in the ocw-studio API that provides the list of new courses, or a problem with the import of these courses. 

### Screenshot or Screencast

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/430126/152210541-7efb807e-b56c-4884-bd0d-447814726a5e.png">

**Comment by ChristopherChudzicki** [comment]
@pdpinch I believe that these are actually two separate courses, although only one of them is really visible on current ocw due to redirects:
```
course 1: 10-01-ethics-for-engineers-spring-artificial-intelligence-spring-2020
course 2: 10-01-ethics-for-engineers-spring-2020
```

- Both courses have backups in `ocw-content-storage` s3 bucket 
- the course content is slightly different
- current ocw redirects `course2 --> course1`, i.e., [`https://ocw.mit.edu/courses/chemical-engineering/10-01-ethics-for-engineers-spring-2020/`](https://ocw.mit.edu/courses/chemical-engineering/10-01-ethics-for-engineers-spring-2020/) redirects to the `-artificial-intelligence-spring-2020` version 

I'm not sure what we want to do here. I can think of a few options:
1. Delete the invisible version (course2)
2. Skip migrating the invisible version (course2)
3. Migrate both courses, but keep course2 unpublished or something so that it doesn't show up in API results like "recently published"

There could also be more of these re-direct duplicates... @blarghmatey Is this something that's easy for you to check?

**Comment by pdpinch** [comment]
There’s only one version in Plone. I suspect that the course title changed at some point and that lead to the creation of a new folder in S3. 

Can you check the dates on the files and inside the metadata to work out which one is more recent?

If I’m right, then I think we should remove the older one from S3 and delete it from studio as well. 

(If I am right, I’m surprised this hasn’t happened before)

**Comment by ChristopherChudzicki** [comment]
@pdpinch Yes. The current ocw version suffixed `-artifical-intelligence-spring-2020` is the newer version. The input to `ocw-to-hugo` shows
```
10-01-ethics-for-engineers-spring-artificial-intelligence-spring-2020
    "first_published_to_production": "2020/07/21 13:27:18.852 Universal",
    "last_published_to_production": "2021/05/17 20:29:19.120 Universal",

10-01-ethics-for-engineers-spring-2020
    "first_published_to_production": "2020/07/21 13:27:18.852 Universal",
    "last_published_to_production": "2020/07/22 17:00:51.656 Universal",
```
which lines up with the timestamps on s3.

Tomorrow I'll check the name-change that happened today
```
# ait vs ai
res-mas-001-raise-responsible-ait-for-social-empowerment-and-education-spring-2022/
res-mas-001-raise-responsible-ai-for-social-empowerment-and-education-spring-2022/
```

**Comment by pdpinch** [comment]
Another pair of courses:

https://ocw-studio.odl.mit.edu/sites/24-908-creole-languages-and-caribbean-identities-spring-2017/
https://ocw-studio.odl.mit.edu/sites/24-908-creole-language-and-caribbean-identities-spring-2017/

I'm pretty sure the first one is correct, with the plural `languages`

**Comment by mbertrand** [comment]
Unpublished:
https://ocw.mit.edu/courses/24-908-creole-language-and-caribbean-identities-spring-2017/
https://ocw.mit.edu/courses/10-01-ethics-for-engineers-spring-2020/

Currently there are no dupes on the new courses carousel

**Comment by mbertrand** [comment]
@pdpinch any more to to on this issue or should I close it?
