### ISSUE TITLE
some pages in 7.00sc Fundamentals of Biology don't build correctly

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#473]
### Steps to Reproduce

view https://ocw-published.odl.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/pages/biochemistry/macromolecules-lipids-carbohydrates-nucleic-acid/

### Expected Behavior

should have all the content from https://ocw.mit.edu/courses/biology/7-01sc-fundamentals-of-biology-fall-2011/biochemistry/macromolecules-lipids-carbohydrates-nucleic-acid/

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/153926774-4077f7b4-c127-4c91-b04c-6497b6a4feb9.png)

### Related issues

The content loads in studio, but the page doesn't build. This page contains a "check yourself" javascript, so work done in mitodl/ocw-hugo-themes#215 might be relevant.

**Comment by gumaerc** [comment]
@abeglova I dug into this this morning and found that the issue was happening in the `multiple_choice_questions_widget` turndown rule.  There were a number of times parsing the content of `dataSubstring` as JSON failed.  Here's an example:

```
{ "multiList": [ { "ques": 'Which of the following statements is true for phospholipid molecules?<ol type="a">
  <li>The polar end of phospholipids would contain carbon and phosphorous and oxygen.</li>
  <li>The non-polar end of phospholipids would contain almost exclusively carbon and hydrogen.</li>
  <li>The polar end of phospholipids would form hydrogen bonds with water.</li>
  <li>The non-polar end of phospholipids associate with the cytoplasm of the cell.</li>
</ol>', "ans": "a,b,c", "ansSel": ["a,b,c, and d", "b,c,d", "a,c"], "ansInfo": "" }, { "ques": 'Which of the following
statements is true for carbohydrate molecules? <ol type="a">
  <li>The general structure can abbreviated as (CH<sub>2</sub>O)n.</li>
  <li>A disaccharide can be formed by a condensation reaction between two glucose molecules.</li>
  <li>Carbohydrates can be used as an energy source for cells.</li>
  <li>Carbohydrates can be used as a structural molecule.</li>
</ol>', "ans": "a,b,c, and d", "ansSel": ["a,b", "c,d", "b,c"], "ansInfo": "" }] }
```

It seems that this is an issue with shoving HTML into a JSON property and quotations not being escaped prior to that.  I would agree that this page should be re-authored, but we don't have an interface within `ocw-studio` for authoring quizzes yet do we?

**Comment by abeglova** [comment]
Yeah, if you look in the comments we figured out it was the quizzes a few weeks ago. There isn't a way to author quizzes to ocw-studio and few months ago Ferdi and Peter said we do not plan to support quizzes in ocw courses. @Ferdi, let me know if that changed.

We can consider supporting a hide/show text shortcode in ocw-studio/ocw courses since that wouldn't be too hard to implement and can be used for other things in addition to quizzes.

**Comment by dseaton** [comment]
Comments: 1) we will not support creating new quizzes for the foreseeable future; 2) we do need a way to either fix or remove the broken quizzes, specifically, so the other content on a page is available.

@gumaerc I am having a hard time interpreting what is HTML in the example you sent. Are you talking about <li>, <ol>, etc? Or am I missing the error.

**Comment by gumaerc** [comment]
@dseaton Basically it seems as if this course is unique in that the quizzes have HTML in their questions and answers.  The ordered list is just one example.  I have some code ready that will fix them, so I could put up a PR to fix it and we could re-import just this one course to fix the quizzes, or we could remove them.  The HTML causes a problem because JSON strings need to be formatted with the keys and values both being surrounded in double quotes like:

```
valid JSON:
{
  "key": "value"
}

invalid JSON:
{
  "key": '<span class="big">value</span>'
}
```
